name: Build APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build release APK
      run: ./gradlew assembleRelease --stacktrace
      
    - name: Sign artifact
      id: signArtifact
      uses: r0adkll/sign-android-release@v1.0.1
      with:
        releaseDirectory: app/build/outputs/apk/release
        alias: ${{ secrets.KEYALIAS }}
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      
    - name: Upload release APK
      uses: actions/upload-artifact@v2.2.0
      with:
          name: app
          path: $SIGNED_RELEASE_FILE
